server:
  port: 8080
  servlet:
    context-path: /cloud


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diploma
    username: ivan
    password: 715820

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  main:
    allow-circular-references: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  token:
    secret: "secret"
    expiration: 18000

cors:
  origins: 'http://localhost:8080'
  methods: '*'
  headers: '*'
  credentials: true
